# Array object attributes :-
### 1. .shape

In [2]:
import numpy as np

arr = np.array([1,2,3,4,5,6])
print(arr)

arr.shape

[1 2 3 4 5 6]


(6,)

### 2. .ndim

In [4]:
arr2 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr2)

arr2.ndim

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


3

### 3. .size

In [7]:
arr3 = np.random.randint(3,4,size=(3,3))
print(arr3)

print(arr3.size)
# check for the orevious one
arr2.size 

[[3 3 3]
 [3 3 3]
 [3 3 3]]
9


8

### 4. .itemsize

In [15]:
arr4 = np.random.rand(3,2)
print(arr4)

print(arr4.itemsize)

# let's convert the array in integer and check the itemsize
print(arr4.astype('int').itemsize)

[[0.27913457 0.98844726]
 [0.74013469 0.94619972]
 [0.93356436 0.00909747]]
8
4


### 5. .dtype

In [19]:
print(arr3.dtype)

print(arr4.dtype)


int32
float64


---
# Array object methods
### 1. .astype('_____')

In [20]:
# check the 4th attribute, astype() method is already used over there

### 2. .reshape(r,c) {same}

In [24]:
print(arr2)

print("\n")

print(arr2.reshape(2,4))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


[[1 2 3 4]
 [5 6 7 8]]


### 3. .min() & .max()

In [25]:
print(arr4.min())
print(arr4.max())

0.009097468358561844
0.9884472632935812


### 4. .argmin() & .argmax()

In [26]:
print(arr4.argmin())
print(arr4.argmax())

5
1
