# Numpy Opeartions :-
---
## Unary operations
### 1. Array/matrix additon & substraction

In [39]:
import numpy as np

arr1 = np.arange(6)
arr2 = np.arange(6, 12)
print(arr1)
print(arr2,'\n')

print(arr1 + arr2)
print(arr1 - arr2)

[0 1 2 3 4 5]
[ 6  7  8  9 10 11] 

[ 6  8 10 12 14 16]
[-6 -6 -6 -6 -6 -6]


### 2. Array/Matrix multiplication (vector product)

In [40]:
# In arrays (one-dimensional), we can simply apply '*' operation in it :
print(arr1 * arr2,'\n')

#  In matrices, we can perform the same operation  and it will multiply the elements of same positon and place them in the smae order matrix
arr3 = np.arange(6).reshape(2,3)
arr4 = np.arange(6,12).reshape(2,3)

print(arr3)
print(arr4,'\n')

print(arr3*arr4)


[ 0  7 16 27 40 55] 

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]] 

[[ 0  7 16]
 [27 40 55]]


### 3. Scalar multiplication 

In [41]:
# as simple it sounds , it multiplies a scalar to each element of array or matrix
print(arr3*6)

[[ 0  6 12]
 [18 24 30]]


### 4. Comparison Operation

In [42]:
# here we use conditional operators on array, which returns the boolean array of same order
# Conditonal operators will be >, <, =+
print(arr3)

print(arr3 >2,'\n')

# Basically conditional statement applied on array will return a boolean array
print(arr3 % 2 == 0,'\n')

# we can also compare two arrays of same order using conditional operators

print(arr3)
print(arr4,'\n')

print(arr3 < arr4)



[[0 1 2]
 [3 4 5]]
[[False False False]
 [ True  True  True]] 

[[ True False  True]
 [False  True False]] 

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]] 

[[ True  True  True]
 [ True  True  True]]


### 5. Matrices Dot Product

In [43]:
# this operations is of the most useful operations used in so many places and is one of the fundamental operations used matrices (from mathematics perspective)
arr5 = np.arange(6).reshape(2,3)
arr6 = np.arange(6,12).reshape(3,2)

## here is the catch if A -> (m,n) then B should be (n, Z)
# it means the no. of columns of first should be equal to the no. of rows of second matrices
print(arr5.dot(arr6),'\n')

print(arr6.dot(arr5))



[[ 28  31]
 [100 112]] 

[[21 34 47]
 [27 44 61]
 [33 54 75]]


Note :- there are some more methods such as :
1. .min() and .max()
2. .sum()
3. .mean() / .average()
4. .std() {stndard deviation}

and we can can calculate for only rows or columns by using "axis" attribute
1. for rows -> (axis = 0)
2. for columns -> (axis = 1)



In [44]:
print(arr6,'\n')

print(arr6.mean(),'\n')

# now to get mean of only rows :-
print(f'arr6 mean of rows: {arr6.mean(axis=1)}')
# and for columns :-
print(f'arr6 mean of columns: {arr6.mean(axis=0)}')



[[ 6  7]
 [ 8  9]
 [10 11]] 

8.5 

arr6 mean of rows: [ 6.5  8.5 10.5]
arr6 mean of columns: [8. 9.]


---
## Universal operations (static operations)
as per OOP, static functions are those functions which are not associated to any object, it means it doesn't use instance variables (such as 'self') for accesing object.

you need to pass the object itslef in order to use the fucntions.

one of the reason they were built like this because these functions are more complex the unary methods. let's take median for example, it's much complicated then mean, becuase it involves :-
- sorting
- considering even/odd lengths
- complicated multiple axis handling
that's the reason it was built as standalone functions, and most of these functions have same reasoning.

### 1.np.median()

In [45]:
print(arr6,'\n')

print(np.median(arr6))
print(np.median(arr6,axis=0))

[[ 6  7]
 [ 8  9]
 [10 11]] 

8.5
[8. 9.]


### 2. np.sin('radians') 
similar for cos, and tan (trignometric functions)

In [46]:
x = np.array([0,1,2,3,4])
print(np.sin(x))


[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]


### 3. np.log() , np.exp() and np.sqrt()

In [47]:
print(np.exp(x))
print(np.log(x+1))  # to avoid log(0)

print(np.sqrt(x))

[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         1.         1.41421356 1.73205081 2.        ]
