# Reshaping methods
    1. .ravel() :

In [4]:
import numpy as np

arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
print(arr1.shape)

print(arr1.ravel())  # it converts multi-dim array to 1-d array

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
[1 2 3 4 5 6 7 8 9]


    2. Reshape() 

In [6]:
arr1.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

    3. .transpose() :

In [7]:
arr1.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

    4. np.hstack((A,B)) and np.vstack((A,B))

In [14]:
arr2 = np.array([[10,11,12],[13,14,15],[16,17,18]])
arr3 = np.hstack((arr1,arr2))

print(arr3,'\n')

arr4 = np.vstack((arr1,arr2))
print(arr4)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]] 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


    5. np.hsplit(arr, divisons)  and np.vsplit(arr, divisions) :

In [19]:
split_arr3 = np.hsplit(arr3, 3)
print(split_arr3,'\n')

split_arr4 = np.vsplit(arr4, 2)
print(split_arr4)

[array([[1, 2],
       [4, 5],
       [7, 8]]), array([[ 3, 10],
       [ 6, 13],
       [ 9, 16]]), array([[11, 12],
       [14, 15],
       [17, 18]])] 

[array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]), array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])]


note :- if A -> (m,n) and 'n' is not divisible by 'divisons' parameter entered, it will throw error.

for such cases use :-

    6.np.array_split(arr, divisions)

In [22]:
arr5 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
np.array_split(arr5, 3)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9]]),
 array([[10, 11, 12]])]