## 1. Fancy Indexing
when there is a matrix (2D array), in order to slect custom rows and columns we use fance indexing.

In [4]:
import numpy as np

arr1 = np.arange(24).reshape(6,4)
print(arr1,'\n')
print(arr1[[0,3,5]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

[[ 0  1  2  3]
 [12 13 14 15]
 [20 21 22 23]]


## 2. Boolean masking
when we put conditions in the array it returns a boolean array. now if put the condition statements as indexing in the array, it will give you the elements of array which satisfy the condition.

now for boolean masking, we equate the statement with the desired value (used to eqaute with "0")

In [13]:
arr2 = np.random.randint(25,50,size = (5,5))
print(arr2,'\n')

print(arr2>35,'\n')
print(arr2[arr2>35],'\n')

arr2[arr2>35] = 0
print(arr2)

[[48 40 42 46 45]
 [42 43 36 29 31]
 [29 41 48 29 45]
 [39 45 43 33 34]
 [34 38 34 26 36]] 

[[ True  True  True  True  True]
 [ True  True  True False False]
 [False  True  True False  True]
 [ True  True  True False False]
 [False  True False False  True]] 

[48 40 42 46 45 42 43 36 41 48 45 39 45 43 38 36] 

[[ 0  0  0  0  0]
 [ 0  0  0 29 31]
 [29  0  0 29  0]
 [ 0  0  0 33 34]
 [34  0 34 26  0]]
