## Broadcasting 

whenever we apply operations on two arrays such as addition & substraction, we always consider that dimensions of arrays are same. but what if the dimensions are not same instead they are different, that's where broadcating comes into the picture :-

here the explanation is quite difficult so I prefer you to watch this video from campusx on broadcasting :-
<br>
<br>
[Broadcating video by CampusX](https://www.youtube.com/watch?v=LaKAA7Z84so&t=7s)

In [18]:
import numpy as np

arr1 = np.arange(12).reshape(3, 4)
arr2 = np.array([10, 20, 30, 40])

print(arr1 + arr2,'\n')

# lets see the other cases of broadcasting
arr3 = np.array([[1], [2], [3]])
print(arr1 + arr3)

# another example
arr4 = np.array([[100], [200], [300], [400]])
print('\n', arr2 + arr4)

# now this one is specially interesting
arr5 = np.array([1, 2, 3])

# print('\n', arr1 + arr5)  
# this will raise an error due to incompatible shapes

# but if we reshape arr5 to (3,1) it will work
arr5_reshaped = arr5.reshape(3, 1)
print('\n', arr1 + arr5_reshaped)

# now if arr6 is (4,1) but arr7 is (1,4), then it will work too
arr6 = np.array([[1], [2], [3], [4]])
arr7 = np.array([[10, 20, 30, 40]])
print('\n', arr6 + arr7)


[[10 21 32 43]
 [14 25 36 47]
 [18 29 40 51]] 

[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]]

 [[110 120 130 140]
 [210 220 230 240]
 [310 320 330 340]
 [410 420 430 440]]

 [[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]]

 [[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]
 [14 24 34 44]]
