## Numpy
one of the essential libraries used in the field of data science, machine learning and AI. it is used for mathematical and scientific calculations for engineering and data science programming.
it's main features are :-
- it's C/C++ and Fortran code based => extremely fast
- it uses concepts of linear algebra
- all the advanced ML libraries are built over NumPy such as : Scikit-learn, TensorFlow, SciPy, Pytorch and so on. 

🔥 these are the first steps of starting out with NumPy :-
	
    1. import numpy
	2. print the version of it
---

In [1]:
import numpy as np
print(np.__version__)

1.26.4


---
## NumPy arrays :-
we have already these two things :-
- Vectors : 1-D arrays
- Matrices : 2-D arrays
✨now let's write our first NumPy array :-

In [20]:
lst = [1,2,3,4]
arr = np.array(my_list)

print(arr, type(arr))

[1 2 3 4] <class 'numpy.ndarray'>


### Matrix from nested lists :-

In [19]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
matrix = np.array(matrix)

print(matrix, type(matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>


### Arrays from tuple

In [23]:
tup = (1,2,3)
tup2 = np.array(tup)

print (tup , type(tup))

(1, 2, 3) <class 'tuple'>
