## Creating arrays with built-in methods :-

In [1]:
import numpy as np

### 1. arange(start, stop, step)

In [2]:
arr = np.arange(0,5,1)
print(arr)

[0 1 2 3 4]


### 2. zeros(vals) or zeros((rows,cols))

In [3]:
arr2 = np.zeros((5,5))
arr2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 3. Ones() {same params as above}

In [4]:

arr3_1 = np.ones(4)
print(arr3_1,"\n")


arr3_2 = np.ones((3,4))
print(arr3_2)

[1. 1. 1. 1.] 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 4. identity(dim) or eye(dim)

In [5]:
arr4 = np.identity(5)
arr4

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 5. linspace(start, stop, divisions)

In [6]:
arr5 = np.linspace(10,20,11)
arr5

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

### 6. rand() {same v or r,c}

In [7]:
arr6 = np.random.rand(2,3)
arr6

array([[0.33957765, 0.44174753, 0.4432125 ],
       [0.32343591, 0.75344691, 0.67416523]])

### 7. randn() {same}

In [8]:
arr7 = np.random.randn(5)
arr7

array([-0.15737395, -0.86456811, -0.88807653, -2.10141445,  0.93703471])

### 8. randint(start, stop, size = (r,c)) 

In [9]:
arr8 = np.random.randint(1,4,size=(3,3))
arr8

array([[2, 3, 2],
       [1, 1, 3],
       [3, 2, 1]])

### 9. a = b.copy()

In [10]:
arr9 = np.copy(arr8)
arr9

array([[2, 3, 2],
       [1, 1, 3],
       [3, 2, 1]])